language: node_js
node_js:
  - 'node'
cache: npm

jobs:
  include:
    - stage: build
      os: linux
      addons:
        apt:
          packages:
          - libxtst-dev
      # before_script:
      # - npm run build
      after_script:
      - ls
    - stage: build
      os: windows
      # before_script:
      # - npm run build
      after_script:
      - dir
      